# Desktop monitor configuration
# Run `swaymsg -t get_outputs` to discover output names

set $output_primary DP-2
set $output_secondary HDMI-A-2
set $output_tertiary DP-1

# output positions (left to right: secondary | primary | tertiary)
output $output_secondary resolution 1920x1080 position 840,0 transform 90
output $output_primary resolution 2560x1440@164.958Hz position 1920,0
output $output_tertiary resolution 3840x2160 position 4480,0 transform 90 scale 1.1

output $output_primary allow_tearing yes
output $output_primary max_render_time off

# bind workspaces to monitors
workspace "0: GAMES" output $output_primary
workspace "2: WEB" output $output_primary
workspace "3: DEV" output $output_primary
workspace "4: CLOUD" output $output_tertiary
workspace "7: MISC" output $output_tertiary
workspace "1: MESSAGES" output $output_secondary

# Required for steam games
exec xrandr --output $output_primary --primary
