set $output_primary HDMI-A-1

output $output_primary resolution 1920x1080

# Override workspace keybindings
bindsym --no-warn $mod+1 workspace "1: KODI"
bindsym --no-warn $mod+2 workspace "2: WEB"
bindsym --no-warn $mod+3 workspace "3: JELLYFIN"

bindsym --no-warn $mod+Shift+1 move container to workspace "1: KODI"
bindsym --no-warn $mod+Shift+2 move container to workspace "2: WEB"
bindsym --no-warn $mod+Shift+3 move container to workspace "3: JELLYFIN"

# Window assignments
assign [app_id="Kodi"] workspace "1: KODI"
assign [app_id="com.github.iwalton3.jellyfin-media-player"] workspace "3: JELLYFIN"

# Media keys
bindsym XF86AudioRaiseVolume exec pactl set-sink-volume @DEFAULT_SINK@ +5%
bindsym XF86AudioLowerVolume exec pactl set-sink-volume @DEFAULT_SINK@ -5%
bindsym XF86AudioMute exec pactl set-sink-mute @DEFAULT_SINK@ toggle
bindsym XF86AudioMicMute exec pactl set-source-mute @DEFAULT_SOURCE@ toggle
bindsym XF86AudioPlay exec playerctl play-pause
bindsym XF86AudioNext exec playerctl next
bindsym XF86AudioPrev exec playerctl previous
bindsym XF86AudioStop exec playerctl stop
